# Project information
site_name: mkdocs-obsidian-support-plugin
site_url: https://pypi.org/project/mkdocs-obsidian-support-plugin/
site_description: >-
  A MkDocs plugin that supports obsidian to mkdocs convert

#Repository
repo_name: ndy2/mkdocs-obsidian-support-plugin
repo_url: https://github.com/ndy2/mkdocs-obsidian-support-plugin

theme:
    name: 'material'
    font:
      text: Roboto
      code: Roboto Mono

# Extensions
markdown_extensions:
  # admonition
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  # image link
  - md_in_html
  - attr_list

  # content tab
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

  # general
  - toc:
      permalink: true

plugins:
  - obsidian-support