# Project information
site_name: mkdocs-obsidian-support-plugin
site_url: https://pypi.org/project/mkdocs-obsidian-support-plugin/
edit_uri: blob/main/docs/
site_description: >-
  A MkDocs plugin that supports obsidian to mkdocs convert

#Repository
repo_name: ndy2/mkdocs-obsidian-support-plugin
repo_url: https://github.com/ndy2/mkdocs-obsidian-support-plugin

theme:
  name: 'material'
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.copy
    - content.action.view

# Extensions
markdown_extensions:
  # admonition
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  # image link
  - md_in_html
  - attr_list

  # content tab
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

  # Caret, Mark & Tilde
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

  # footnotes
  - footnotes

  # general
  - toc:
      permalink: true

plugins:
  - obsidian-support

nav:
  - index.md
  - Features:
      - Admonition:
          - features/admonition/index.md
          - features/admonition/demo.md
      - Image Link: features/image-link/index.md
