name: ci
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: run pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Set up Python 3 ⚙️ 🐍
        uses: actions/setup-python@v2

      # retrieve your distributions here
      - run: pip install -r requirements.txt
      - run: python setup.py sdist

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-without-markdown
          path: |
            dist
            !dist/**/*.md

      # run pytest
      - run: cd test; python -m pytest

  release:
    name: Upload release to PyPI and Deploy Github Pages
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/mkdocs-obsidian-support-plugin
    permissions: write-all
    steps:
      # retrieve your distributions here
      - name: Download math result for job 2
        uses: actions/download-artifact@v4
        with:
          name: Archive artifacts

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      # deploy github pages
      - run: pip install mkdocs-material
      - run: pip install mkdocs-glightbox
      - run: pip3 install mkdocs-exclude
      - run: pip install mkdocs-kroki-plugin
      - run: pip install mkdocs-obsidian-support-plugin
      - run: mkdocs gh-deploy --force
