name: ci
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/mkdocs-obsidian-support-plugin
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      # retrieve your distributions here
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Set up Python 3 ⚙️ 🐍
        uses: actions/setup-python@v2

      - run: pip install mkdocs-material
      - run: pip install mkdocs-glightbox
      - run: pip3 install mkdocs-exclude
      - run: pip install mkdocs-kroki-plugin
      - run: pip install mkdocs-obsidian-support-plugin
      - run: mkdocs gh-deploy --force
