name: ci
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Set up Python 3 ⚙️ 🐍
        uses: actions/setup-python@v2

      - run: pip install mkdocs-material
      - run: pip3 install mkdocs-exclude
      - run: pip install mkdocs-kroki-plugin
      - run: pip install mkdocs-obsidian-support-plugin
      - run: mkdocs gh-deploy --force
