name: ci
on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Set up Python 3 ⚙️ 🐍
        uses: actions/setup-python@v2

      - run: pip install mkdocs==1.1.2
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
